language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-rakuten-yo' ]; then cd .. && eval "mv $currentfolder generator-rakuten-yo" && cd generator-rakuten-yo; fi
